# .NET Desktop Application Build Workflow
# This workflow builds a .NET 8 WPF application

name: .NET Desktop Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore WinSwitch.sln

    # Build the application
    - name: Build application
      run: dotnet build WinSwitch.sln --configuration ${{ matrix.configuration }} --no-restore

    # Upload build artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: WinSwitch-${{ matrix.configuration }}
        path: |
          WinSwitch.App/bin/${{ matrix.configuration }}/
          !WinSwitch.App/bin/${{ matrix.configuration }}/**/*.pdb
